### PR TITLE
Proposing less ambiguous messaging about video usage at Denhac

### PR DESCRIPTION
**Pull request by flippest**

### CODE REVIEW

**Comment by whitehot6er** [comment]
+1 wording is overly broad and gives denhac way too much authority over how it can use security camera footage or any other media without input from the subjects. Seems antithetical to denhacs history of being privacy/security focused.

**Review by Evan-Robertson — CHANGES_REQUESTED** [review]
@flippest - Appreciate your PR and contribution. I'm +1 on discussion and any revisions that accurately aligns language with how cameras are actually used at denhac. 

For context: The language in the camera section was borrowed from a waiver that's been through legal review in Colorado. It's unrelated to changes required by our insurance but we felt should be included in the revised waiver that all members and guests would need to sign for two reasons.

1) We've had discussions about improving transparency that cameras in denhac the building record both audio and video in addition to signs posted at building entrances and around denhac. Previously, camera language was covered when members checked the "I agree" box when signing up. We wanted to make it even more transparent and get explicit consent from both members and guests going forward. 

2) It's not just about security cameras. It also legally covers denhac for any other recordings made for events, presentations, cameras on the 3d printers, etc. and how that footage may end up be used. For example, a member gives a tech talk in the classroom. They communicate it will also be streamed and they might also post it to youtube after. "for any purpose" in this waiver covers all that instead of the speaker needing to collect consent from everyone in attendance plus the person who randomly walks into the camera/can be heard in the background.

I don't believe your proposed change to "for safety and security purposes" adequately covers the second case.  It also should better define other reasons security camera footage may be reviewed such as tracking down missing tools or mediating conflict. Can you please look into the potential legal implications of changing to more narrow wording and revise PR.

For what it's worth, there's no nefarious intent behind the broad scope language. I'm cognizant of the security and privacy mindset and individuals at denhac. I consider myself one of them. I still proposed and voted for this language to be included in our waiver to best protect denhac.

**Comment by tilver** [comment]
Here are my current working ideas:
denhac is covered by the current version, but it's very onerous privacy-wise.  
Libraries seem to have a good (IMHO) feel for meeting security needs while striving to protect privacy (I'd like to use some of their language to form this policy)
Objections to someones likeness being on social media shouldn't preclude them from participating in the space. 

Split the surveillance camera content, standing stream and event content policies.
  - Security cams will only be used to enhance physical security of the space  
  - Transparency logging and publishing.  The footage was accessed to investigate a theft etc.
  - Only accessed by a minimum of two board members?
  - Probably like to see audio go away in the name of privacy  (It'd be nice to be able to take a conference call without it being recorded).  Would a white noise generator be a violation of space rules in spirit?
  - Preservation Period of... 3 years (need legal advice here)

Events with recording will be announced in advance and at time of event.  
  - (3 foot signs saying recording in progress or something)
  - Intention of preservation length

Standing streams should be clearly marked.  (possible 3D Printer streams / weather station / ???)
 - Signage on Door to device?  (yes we have some on the front door, but additional can't hurt)

No third party transfer (might block YouTube/Facebook uploads... OK) of security content (All content?).

Subpoena required to disclose content? 
- Perhaps board vote?, but this should be spelled out and followed. 
- If a member requests the footage, do they get it without subpoena?

**Comment by tilver** [comment]
Just for fun I ran it through chat gpt.   Looks like a decent base.

**Camera Policy for Denhac**

**Effective Date:** [Insert Effective Date]

**1. Introduction**

Denhac, hereinafter referred to as "the organization," is committed to providing a safe and secure environment for its members, visitors, and the protection of their privacy. This Camera Policy outlines the guidelines and rules for the use of security cameras, special event media content, and full-time streaming of device status within the organization's premises. This policy aims to strike a balance between the organization's security needs and the privacy rights of its members.

**2. Security Camera Content**

**2.1. Purpose**
Security cameras are installed within the organization's premises to enhance security and ensure the safety of its members and property.

**2.2. Scope**
This section covers the rules and guidelines regarding the use of security cameras.

**2.3. Rules and Guidelines**
- Security cameras will only be used in areas where there is a legitimate need for surveillance, such as entrances, common areas, and sensitive locations.
- The placement of security cameras will avoid capturing private spaces, restrooms, and areas where individuals have a reasonable expectation of privacy.
- The organization will clearly indicate the presence of security cameras with visible signs to inform individuals that they may be recorded.
- Access to security camera footage will be restricted to authorized personnel for security purposes, and such access will be logged and monitored.
- Security camera footage will not be used for any purpose other than security and safety unless required by law or approved by the organization's leadership.

**3. Special Event Media Content**

**3.1. Purpose**
The organization may capture and use media content during special events for promotional and archival purposes.

**3.2. Scope**
This section covers the rules and guidelines for capturing and using media content during special events organized by the organization.

**3.3. Rules and Guidelines**
- Prior consent will be obtained from individuals who may be captured in media content during special events. Consent forms will clearly state the purpose of the media usage.
- Individuals who do not wish to be captured in media content may opt-out and will not be included in promotional material.
- Media content captured during special events may be used for promotional purposes, including but not limited to the organization's website, social media, and marketing materials.
- Media content will be stored securely and retained for a reasonable period, after which it will be deleted, unless required by law or approved by the organization's leadership.

**4. Full-Time Streaming of Device Status**

**4.1. Purpose**
The organization may stream device status information for monitoring and maintenance purposes.

**4.2. Scope**
This section covers the rules and guidelines for streaming device status information.

**4.3. Rules and Guidelines**
- Full-time streaming of device status will be limited to devices essential for the operation of the organization's premises and services.
- Access to device status streams will be restricted to authorized personnel responsible for monitoring and maintenance.
- Device status information will not be used for any purpose other than monitoring and maintenance, and will not include any personal or private data.

**5. Compliance and Enforcement**

The organization is committed to ensuring compliance with this Camera Policy. Violations of this policy may result in disciplinary action, including but not limited to suspension of privileges or expulsion from the organization. The organization reserves the right to amend this policy as needed, and all members will be notified of any changes.

**6. Questions and Concerns**

If you have any questions or concerns regarding this Camera Policy, please contact the organization's leadership or designated privacy officer.

By remaining a member of Denhac, individuals acknowledge their understanding of and agreement to abide by this Camera Policy.

**Pull request closed without merging**
